---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: rom-bool

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - property:
          name: rom-bool
          operator: is-true
    flagValue:
      - percentage: 40
        option: true
      - percentage: 60
        option: false
  - allOf:
      - property:
          name: rom-string
          operator: in-array
          operands:
            - "1"
            - "2"
            - "4"
            - "5"
            - "6"
            - "7"
      - property:
          name: rom-number
          operator: eq
          operands:
            - 123
    flagValue: true
